Controllers/NotebookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NTR02.Data;
using NTR02.Models;
using static NTR02.NotebookControl;

namespace NTR02.Controllers
{
    public class NotebookController : Controller
    {
        private readonly NotebookContext _context;

        public NotebookController(NotebookContext context)
        {
            _context = context;
        }

        // GET: Notebook
        public async Task<IActionResult> Index()
        {
            CleanNoteCategories();
            ViewBag.Notes = await _context.Note.ToListAsync();
            ViewBag.Categories = await _context.Category.ToListAsync();
            ViewBag.NoteCategories = await _context.NoteCategory.ToListAsync();
                        
            return View();
        }
        // GET: Notebook/Create
        public IActionResult Create()
        {
            ViewBag.Categories = FindNewNoteCategories(0);
            return View();
        }

        // POST: Notebook/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoteID,Title,Description,NoteDate")] Note note,
        string Category)
        {
            if (ModelState.IsValid)
            {              
                if(_context.Note.Where(notie =>notie.Title == note.Title).Count() ==0)               
                    _context.Add(note);
                else
                    return View(note);
                await _context.SaveChangesAsync(); 
                SubmitNoteCategories(note.NoteID);
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notebook/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            /*if (id == null)
            {
                return NotFound();
            }*/

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }
            ViewBag.Categories = FindNewNoteCategories(id);
            return View(note);
        }

        // POST: Notebook/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoteID,NoteDate,Title,Description")] Note note)
        {
            if (id != note.NoteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.NoteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notebook/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.NoteID == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notebook/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Note.FindAsync(id);
            _context.Note.Remove(note);
            await _context.SaveChangesAsync();
            updatePage();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateCategory(string category, int id, string view, string submit)
        {
            if(submit == "Add")
                AddCategory(category,id);
            else if(submit == "Remove" )
                RemoveCategory(category,id);
            else
                return RedirectToAction(nameof(Index));
            
            if(view == "Create")
                return RedirectToAction(nameof(Create));
            else
                return RedirectToAction(nameof(Edit),new{id = id});
            
        }
        public async void AddCategory(String category, int id)
        {
            if(_context.Category.Where(cat =>cat.Name == category).Count() ==0)               
            {
                Category cat = new Category();
                cat.Name = category;
                _context.Add(cat);
                await _context.SaveChangesAsync();
            }
            int catID = _context.Category.Where(cat => cat.Name == category).First().CategoryID;    
            if(_context.NoteCategory.Where(cat => cat.NoteID == id && cat.CategoryID == catID).Count() == 0)
            {
                NoteCategory newNCat = new NoteCategory();            
                newNCat.CategoryID = catID;
                newNCat.NoteID =id;
                _context.Add(newNCat);
                await _context.SaveChangesAsync();
            }
            
        }
        public async void RemoveCategory(String category, int id)
        {
            if(_context.Category.Where(cat =>cat.Name == category).Count() ==0)
                return;
            int catID = _context.Category.Where(cat =>cat.Name == category).First().CategoryID;
            if(_context.NoteCategory.Where(cat => cat.NoteID == id && cat.CategoryID == catID).Count() != 0)
            {
                NoteCategory toDelete  = _context.NoteCategory.Where(cat => cat.NoteID == id && cat.CategoryID == catID).First();
                _context.NoteCategory.Remove(toDelete);
                await _context.SaveChangesAsync();
            }
        }

        public IActionResult Filter(DateTime from, DateTime to, string category)
        {
            if(DateTime.Compare(from,to) > 0)
                return RedirectToAction(nameof(Index));
            fromDate = from;
            toDate = to;
            filterCat = category;
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DeleteFilter()
        {
            SetDefaults();
            filteredNotesCount = _context.Note.Count();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult NextPage()
        {
            if((page)* 10 < filteredNotesCount)
                page++;
            return RedirectToAction(nameof(Index));
        }
         public IActionResult PreviousPage()
        {
            if(page > 1)
                page--;
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(int id)
        {
            return _context.Note.Any(e => e.NoteID == id);
        }

        private void updatePage()
        {
            if(page*10 == filteredNotesCount +9 && page != 1)
                page--;
        }
        private List<Category> FindNewNoteCategories(int id)
        {
            List<Category> newNoteCategories = new List<Category>();
            foreach(var noteCategory in _context.NoteCategory.Where(nCat => nCat.NoteID == id))
            {
                newNoteCategories.Add(_context.Category.Find(noteCategory.CategoryID));
            }
            return newNoteCategories;
        }
        private async void CleanNoteCategories()
        {
            
            foreach(var nCatie in _context.NoteCategory.Where(nCat => nCat.NoteID ==0))
            {
                _context.NoteCategory.Remove(nCatie);
            }
            await _context.SaveChangesAsync(); 

        }
        private async void SubmitNoteCategories(int id)
        {
            foreach(var nCatie in _context.NoteCategory.Where(nCat => nCat.NoteID ==0))
            {
                
                nCatie.NoteID = id;
                _context.NoteCategory.Update(nCatie);
            }
            await _context.SaveChangesAsync(); 
        }
    }
}

Views/Notebook/Create.cshtml
@model NTR02.Models.Note

@{
    ViewData["Title"] = "Create";
}
<div class="well">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-sm-1">Title: </div>            
            <div class="col-sm-9">
                <input asp-for="Title" type="text" style = "width:500px" />
            </div>
            <div class ="col-sm-2">
            </div>
        </div>
        <textarea asp-for="Description" type="text" style="width:1100px; height:400px;"> </textarea>
        <div class = "row">
        <div class = "col-sm-5 col-sm-offset-4"> Category:
        </div>
        <div class = "col-sm-3"> Date:
            <input asp-for="NoteDate" />
        </div>
        <hr/>
        </div>
        <div align="right">
            <input type="submit" value="OK" class="btn btn-secondary" />
            <a asp-action="Index" type="button" class="btn btn-secondary">Cancel</a>          
        </div>
    </form>
    <form asp-action="UpdateCategory">
        <div class="row">
            <div class="col-sm-3">
                <select>
                    @foreach(var cat in ViewBag.Categories)
                    {
                        <option> @cat.Name </option>
                    }
                </select>
            </div>
            <div class="col-sm-3">
                <input type ="text" name ="category"/>
            </div>
            <div class="col-sm-3">
                <input type ="submit" name ="submit" value = "Add"/>
                <input type ="submit" name ="submit" value = "Remove"/>
            </div>
        </div>
        <input type= "hidden" name = "id" value = "0" />
        <input type = "hidden" name = "view" value = "Create" />
        
        
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notebook/Delete.cshtml
@model NTR02.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NoteID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Notebook/Edit.cshtml
@model NTR02.Models.Note

@{
    ViewData["Title"] = "Edit";
}

<div class="well">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NoteID" />
            <div class="row">
            <div class="col-sm-1">Title: </div>            
            <div class="col-sm-9">
                <input asp-for="Title" type="text" style = "width:500px" />
            </div>
            <div class ="col-sm-2">
            </div>
        </div>
        <textarea asp-for="Description" type="text" style="width:1100px; height:400px;"> </textarea>
        <div class = "row">
        <div class = "col-sm-5 col-sm-offset-4"> 
        </div>
        <div class = "col-sm-3"> Date:
            <input asp-for="NoteDate" />
        </div>
        <hr/>
        </div>
        <div align="right">
            <input type="submit" value="Save" class="btn btn-secondary" />
            <a asp-action="Index" type="button" class="btn btn-secondary">Cancel</a>          
        </div>
        </form>
        <form asp-action="UpdateCategory">
        <div class="row">
            <div class="col-sm-3">
                <select>
                    @foreach(var cat in ViewBag.Categories)
                    {
                        <option> @cat.Name </option>
                    }
                </select>
            </div>
            <div class="col-sm-3"> Categories:
                <input type ="text" name ="category"/>
            </div>
            <div class="col-sm-5">
                <input type ="submit" name ="submit" value ="Add"/>
                <input type ="submit" name ="submit" value = "Remove"/>
            </div>
        </div>
        <input type= "hidden" name = "id" value = "@Model.NoteID" />
        <input type = "hidden" name = "view" value = "Edit" />
        
        
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notebook/Index.cshtml
@model IEnumerable<NTR02.Models.Note>

@{
    ViewData["Title"] = "Index";
}
@{
    
    DateTime fromDate = NotebookControl.fromDate;
    DateTime toDate = NotebookControl.toDate;
    String currentDate = fromDate.Year.ToString() + '-' + fromDate.Month.ToString("D2") + '-' + fromDate.Day.ToString("D2");
    String maxDate =  toDate.Year.ToString() + '-' + toDate.Month.ToString("D2") + '-' + toDate.Day.ToString("D2");
    String filterCat = NotebookControl.filterCat;
    
    List<NTR02.Models.Note> filteredNotes = new List<NTR02.Models.Note>();
    foreach(var item in ViewBag.Notes)
    {
        
            bool categoriesMatch = false;
            if(filterCat == null)
                categoriesMatch = true;
            else
            {
                foreach(var nCat in ViewBag.NoteCategories)
                {
                    if(categoriesMatch)
                        break;
                    if(nCat.NoteID == item.NoteID)
                    {
                        foreach(var cat in ViewBag.Categories)
                        {
                            if(cat.Name== NotebookControl.filterCat && cat.CategoryID == nCat.CategoryID)
                            {
                                categoriesMatch = true;
                                break;
                            }
                        }
                    }
                }
            }
            if(item.NoteDate >= fromDate && item.NoteDate <= toDate && categoriesMatch)
            {
                if(filteredNotes.Count()==0)
                    filteredNotes.Add(item);
                else
                {
                    int i = 0;
                    do
                    {    
                        if(item.NoteDate <= filteredNotes.ElementAt(i).NoteDate)
                        {
                            filteredNotes.Insert(i,item);
                            break;
                        }
                        i++;
                    }while(i< filteredNotes.Count());
                    if(i==filteredNotes.Count())
                        filteredNotes.Add(item);
                }
            }   
         
    }

    int notesCount = filteredNotes.Count();
    int curPage = NotebookControl.page;
    int displayLimit = curPage * 10 > notesCount ? notesCount: curPage*10;
    NotebookControl.filteredNotesCount = filteredNotes.Count();
    int maxPage = (filteredNotes.Count()-1)/10 +1;
}
 <div class = "well">
            <form asp-action="Filter" asp-controller="Notebook">    
                <div class = "row">
                    <div class="col-sm-3">
                        From: 
                        <input type="date" name = "from" value = @currentDate> 
                    </div>
                    <div class="col-sm-3">
                        To:
                        <input type="date" name = "to" value = @maxDate> 
                    </div>
                    <div class="col-sm-4">
                        Category:
                        <select name = "category">
                            @foreach(var category in ViewBag.Categories)
                            {
                                 <option value="@category">@category.Name</option>
                            }
                            <option value=@null>No Filter</option>
                        </select>
                        
                    </div>
                    <div class="col-sm-2">
                        <div class = "btn-group">
                            <input type="submit" value="Filter">
                            <a asp-action="DeleteFilter" asp-controller="Notebook" class="btn btn-info">Delete Filter</a>
                        </div>
                    </div>

            
                </div>
            </form>
            <table class="table table-striped" >
                <thead >
                <tr>
                    <th>Date</th>
                    <th>Title</th>
                </tr>
                </thead>
                <tbody>

                @for(int i = (curPage - 1) * 10; i<displayLimit ;i++)
                {
                    var item = @filteredNotes.ElementAt(i);
                    
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.NoteDate) 
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Title)
                        <div align="right">
                        <a asp-action="Edit" asp-route-id= "@item.NoteID" class="btn btn-info">Edit</a>
                        <a asp-action="Delete" asp-route-id= "@item.NoteID" class="btn btn-info">Delete</a>
                        </div>
                        </td>
                    </tr>
                    
                }                     
                </tbody>
            </table>

            <hr />
            
            <div class = "row">
                <div class="col-sm-6">
                    <div class="btn-group">
                    <a asp-controller="Notebook" asp-action="Create" type = "button" class="btn btn-info">New</a>
                    </div>
                </div>
                <div class="col-sm-2">
                    <a asp-controller="Notebook" asp-action="PreviousPage" type = "button" class="btn btn-info">Previous Page</a>
                </div>
                <div class ="col-sm-2"> Page: @curPage / @maxPage </div>
                <div class="col-sm-2">
                    <a asp-controller="Notebook" asp-action="NextPage" type = "button" class="btn btn-info">Next Page</a>
                </div>

        
            </div>
            <hr />
            


        </div>
